In [31]:
import numpy as np

In [32]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [33]:
A

array([[10, 10, 11],
       [10,  7,  6],
       [ 9, 10,  7]])

In [34]:
B

array([[-1, -2,  1],
       [ 3,  1,  3],
       [ 0, -1,  2]])

In [35]:
# Поэлементное умножение
A*B

array([[-10, -20,  11],
       [ 30,   7,  18],
       [  0, -10,  14]])

In [36]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 20 -21  62]
 [ 11 -19  43]
 [ 21 -15  53]]


In [37]:
# Матричное умножение
np.dot(A,B)

array([[ 20, -21,  62],
       [ 11, -19,  43],
       [ 21, -15,  53]])

In [38]:
# Матричное умножение
A@B

array([[ 20, -21,  62],
       [ 11, -19,  43],
       [ 21, -15,  53]])

In [39]:
# Порядок умножения AB != BA
B@A

array([[-21, -14, -16],
       [ 67,  67,  60],
       [  8,  13,   8]])

In [40]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 6  7  8  6  5]
 [ 8  5  6  6  6]
 [ 8  9  6  7 10]]
B:
 [[ 1 -2]
 [-2  0]
 [-2  1]
 [-1 -2]
 [ 2 -1]]


In [41]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-20, -21],
       [ -8, -28],
       [ -9, -34]])

In [42]:
# Умножение прямоугольных матриц возможно не в любом порядке
#B@A

In [43]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [44]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-4 -3 -3  2]
 [-4  1  3 -1]
 [-2 -3 -1 -3]
 [ 1 -2 -1 -1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-4 -6  0 -2]
 [-4  2  0  1]
 [-2 -6  0  3]
 [ 1 -4  0  1]]
DA:
 [[-4 -3 -3  2]
 [-8  2  6 -2]
 [ 0  0  0  0]
 [-1  2  1  1]]


In [45]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [46]:
#b@A

In [47]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [48]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [49]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [50]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [51]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [55]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(A@x)

[26 30]


In [56]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(B@A)

[[  2   9  11  14]
 [  8 -10 -14 -11]]


In [58]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([z, y, z])

print(A.T@A)

[[ 6  0  0  2  0]
 [ 0  3 -3  1  0]
 [ 0 -3  3 -1  0]
 [ 2  1 -1  1  0]
 [ 0  0  0  0  0]]


УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [60]:
import pandas as pd
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

display(Count_DF)
display(Price_DF)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [73]:
count = Count_DF.values
price = Price_DF.values
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
ver = np.array([1, 1, 1, 1, 1])
prib = ver-com

In [76]:
display((price*count)@prib)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [75]:
prib = ver-com
prib

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [4]:
n, m = [int(j) for j in input().split()]
A = [[int(el) for el in input().split()] for _ in range(n)]
input()
n, m = [int(j) for j in input().split()]
B = [[int(el) for el in input().split()] for _ in range(n)]
def proizved_mat(A,B):
    if len(A) != len(B[0]):
        print("dim_A != dimB[0]")
    matrix = [[sum([B[j][i]*A[k][j] for j in range(len(B))]) for i in range(len(B[0]))]for k in range(len(A))]
    
    return matrix

matrix = proizved_mat(A,B)
[print(*row) for row in matrix]

48 42 14
33 31 10
36 40 12


[None, None, None]