In [2]:
from sklearn.neighbors import NearestNeighbors

NearestNeighbors

sklearn.neighbors._unsupervised.NearestNeighbors

In [28]:
# Вычисляем квадрат разницы между всеми парами точек
import numpy as np
X = np.array([[0,2],[-2,0],[1,0],[0,-3]])
X_train = np.array([[0,3],[-3,0],[2,0],[0,-2]])
num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))

differences = X[:, np.newaxis, :] - X_train  # Добавляем новую ось для обучающего набора
squared_differences = differences ** 2  # Возводим в квадрат
sum_squared_differences = np.sum(squared_differences, axis=2)  # Суммируем квадраты по всем признакам
dists = np.sqrt(sum_squared_differences)  # Извлекаем корень
y_train = np.array([0,1,0,1])
print(dists)

[[1.         3.60555128 2.82842712 4.        ]
 [3.60555128 1.         4.         2.82842712]
 [3.16227766 4.         1.         2.23606798]
 [6.         4.24264069 3.60555128 1.        ]]


In [29]:
def predict_labels(self, dists, k=1):
    """
    Given a matrix of distances between test points and training points,
    predict a label for each test point.

    Inputs:
    - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
        gives the distance betwen the ith test point and the jth training point.

    Returns:
    - y: A numpy array of shape (num_test,) containing predicted labels for the
        test data, where y[i] is the predicted label for the test point X[i].
    """
    num_test = dists.shape[0]
    y_pred = np.zeros(num_test)
    for i in range(num_test):
        # A list of length k storing the labels of the k nearest neighbors to
        # the ith test point.
        #########################################################################
        # TODO:                                                                 #
        # Use the distance matrix to find the k nearest neighbors of the ith    #
        # testing point, and use self.y_train to find the labels of these       #
        # neighbors. Store these labels in closest_y.                           #
        # Hint: Look up the function numpy.argsort.                             #
        #########################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        #########################################################################
        # TODO:                                                                 #
        # Now that you have found the labels of the k nearest neighbors, you    #
        # need to find the most common label in the list closest_y of labels.   #
        # Store this label in y_pred[i]. Break ties by choosing the smaller     #
        # label.                                                                #
        #########################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

    return y_pred

IndentationError: expected an indented block (3821627162.py, line 41)

In [30]:
num_test = dists.shape[0]
y_pred = np.zeros(num_test)


In [31]:
dists

array([[1.        , 3.60555128, 2.82842712, 4.        ],
       [3.60555128, 1.        , 4.        , 2.82842712],
       [3.16227766, 4.        , 1.        , 2.23606798],
       [6.        , 4.24264069, 3.60555128, 1.        ]])

In [32]:
k=2
for i in range(num_test):
    # Находим индексы ближайших соседей для i-й тестовой точки
    closest_neighbor_indices = np.argsort(dists[i])[:k]
    
    # Получаем метки ближайших соседей
    closest_labels = y_train[closest_neighbor_indices]
    
    # Подсчитываем, какие метки встречаются чаще всего
    counts = np.bincount(closest_labels)
    
    # Находим метку, которая встречается максимальное количество раз
    predicted_label = np.argmax(counts)
    
    # Сохраняем предсказанную метку
    y_pred[i] = predicted_label

In [33]:
y_pred

array([0., 1., 0., 0.])

In [34]:
np.random.laplace

<function RandomState.laplace>

In [ ]:
import numpy as np
X = np.array([[0,2],[-2,0],[1,0],[0,-3]])
X_train = np.array([[0,3],[-3,0],[2,0],[0,-2]])

num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))



In [46]:

differences = X[:, np.newaxis, :] - X_train  
squared_differences = differences ** 2  
sum_squared_differences = np.sum(squared_differences, axis=2)  
dists = np.sqrt(sum_squared_differences)  

In [47]:


X_expand = np.expand_dims(X, axis=1)
X_train_expand = np.expand_dims(X_train, axis=0)

# Вычисляем квадрат разницы между всеми парами точек
squared_differences = (X_expand - X_train_expand) ** 2  # Возводим в квадрат
sum_squared_differences = np.sum(squared_differences, axis=2)  # Суммируем квадраты по всем признакам
dists = np.sqrt(sum_squared_differences)